version: '3.8'

services:
  dms-server:
    build:
      context: ./backend
    container_name: dms_server
    ports:
      - "8080:8080"
    environment:
      SPRING_PROFILES_ACTIVE: "default"
      SPRING_DATASOURCE_URL: jdbc:postgresql://database:5432/${POSTGRES_DB}
      SPRING_DATASOURCE_USERNAME: ${SPRING_DATASOURCE_USERNAME}
      SPRING_DATASOURCE_PASSWORD: ${SPRING_DATASOURCE_PASSWORD}
    volumes:
      - ./logs:/app/logs
    networks:
      - dms-network
    depends_on:
      - database

  frontend:
    build:
      context: ./frontend  # Zeigt auf das Hauptverzeichnis des Frontends
      dockerfile: nginx/Dockerfile  # Zeigt auf das Dockerfile im nginx-Verzeichnis
    container_name: frontend_nginx
    ports:
      - "80:80"                 # Exponiert den Port 80 für Nginx
    depends_on:
      - dms-server              # Wartet, bis das Backend läuft
    networks:
      - dms-network

  database:
    image: postgres:latest
    container_name: postgres_db
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - dms-network

networks:
  dms-network:
    driver: bridge

volumes:
  postgres_data:
