version: '3.8'

services:
  dms-server:
    build:
      context: ./backend  # Zeigt auf das Backend-Verzeichnis
    container_name: dms_server
    ports:
      - "8080:8080"       # Exponiert den Port 8080 für das Backend
    environment:
      SPRING_PROFILES_ACTIVE: "default"
    volumes:
      - ./logs:/app/logs
    networks:
      - dms-network

  frontend:
    build:
      context: ./frontend  # Zeigt auf das Hauptverzeichnis des Frontends
      dockerfile: nginx/Dockerfile  # Zeigt auf das Dockerfile im nginx-Verzeichnis
    container_name: frontend_nginx
    ports:
      - "80:80"                 # Exponiert den Port 80 für Nginx
    depends_on:
      - dms-server              # Wartet, bis das Backend läuft
    networks:
      - dms-network

networks:
  dms-network:
    driver: bridge
